name: ${project.name}
main: jp.azisaba.main.homos.HomoSystem
version: ${project.version}
author: siloneco
description: "Hyper Original Money Operator System."
softdepend: ["Vault"]
api-version: 1.13
commands:
  homo:
    usage: "/{LABEL}"
    permission: homos.command.homo
    aliases: ["homos"]
permissions:
  homos.command.homo:
    default: op
