name: Homos
main: jp.azisaba.main.homos.Homos
version: 1.0.1-beta
author: siloneco
description: "Hyper Original Money Operator System."
softdepend: ["Vault"]
commands:
  homo:
    usage: "/{LABEL}"
    permission: homos.command.homo
    aliases: ["homos"]
permissions:
  homos.command.homo:
    default: op