name: Maven

on: [push]

jobs:
  build:
    name: Build with Java 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: java -version
      - run: mvn --version
      - run: mvn -B package
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  deploy:
    name: Deploy with Java 8
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.MAVEN_REPO_KEY }}
      - uses: actions/checkout@v2
        with:
          repository: AzisabaNetwork/mvn-repo
          path: mvn-repo
      - run: mvn -B -DaltDeploymentRepository=mvn-repo::default::file://mvn-repo deploy
      - run: |
          git config --local user.email 'null@azisaba.net'
          git config --local user.name "$GITHUB_ACTOR"
          git commit -a -m "Deploy @ $(date)"
          git push origin master
        working-directory: mvn-repo
