name: Maven

on: [push]

jobs:
  build:
    name: Build - Java 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: java -version
      - run: mvn --version
      - run: mvn -B package
  deploy:
    name: Deploy - Java 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: java -version
      - run: mvn --version
      - run: git clone git@github.com:AzisabaNetwork/mvn-repo.git
      - run: mvn -B -DaltDeploymentRepository=local::default::file://mvn-repo deploy
      - run: |
          mkdir -pv ~/.ssh
          touch ~/.ssh/id_rsa
          echo "${{ secrets.MAVEN_REPO_KEY }}" > ~/.ssh/id_rsa
      - run: |
          cd mvn-repo
          git add -A
          git commit -m "Deploy @ $(date)"
          git push origin master
